name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
        - name: Generate code coverage
                run: cargo llvm-cov --all-features --workspace --cobertura --output-path cobertura.xml
              - name: Report code coverage
                uses: irongut/CodeCoverageSummary@v1.3.0
                with:
                  filename: cobertura.xml
                  badge: true
                  format: markdown
                  output: both
              - name: Add Coverage PR Comment
                uses: marocchino/sticky-pull-request-comment@v2
                if: github.event_name == 'pull_request'
                with:
                  header: Coverage Report
                  recreate: true
                  path: code-coverage-results.md
              - name: Write to Job Summary
                run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
